version: '3'

services:

  # no logstash in this setup, using elastic agent's instead.
  setup:
    build:
      context: setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - setup:/state:z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      #LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
    networks:
      - elk
      
  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    ports:
      - "5601:5601"
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    healthcheck:
      test: ["CMD", "curl", "-s" ,"-XGET", "http://localhost:5601"]
    networks:
      - elk
    depends_on:
      - elasticsearch 
      
#  logstash:
#    build:
#      context: logstash/
#      args:
#        ELASTIC_VERSION: ${ELASTIC_VERSION}
#    volumes:
#      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,z
#      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,z
#    ports:
      #add ports here if sending logs this way from external sources
#      - "50000:50000"
#      - "5044:5044"
#      - "9600:9600"
#    environment:
#      LS_JAVA_OPTS: -Xms512m -Xmx512m
#      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
#    healthcheck:
#      test: ["CMD", "curl", "-s" ,"-XGET", "http://127.0.0.1:9600"]
#    networks:
#      - elk
#    depends_on:
#      - elasticsearch
      
#  fluentd:
#    build: ./fluentd
#    volumes:
#      - ./fluentd/conf:/fluentd/etc:z
#    links:
#      - "elasticsearch"
#    ports:
#      - "5140:5140/udp"
#      - "24224:24224"
#      - "24224:24224/udp"
#    networks:
#      - elk
#    logging:
#        driver: "json-file"
#        options:
#            max-size: 100m
#            max-file: "5"

networks:
  elk:

volumes:
  setup:
  elasticsearch:
    
