version: '3'

volumes:
  sonarqube-postgres-backups:
  sonarqube-data-backups:
  
services:
  backups:
    image: docker.io/bitnami/postgresql:latest
    container_name: psql-backup
    hostname: psql-backup.testing.io
    command: sh -c 'sleep 30m
             && while true; do
             PGPASSWORD="$$(echo $${POSTGRES_PASS})"
             pg_dump
             -h postgres
             -p 5432
             -d sonarqube
             -U sonar | gzip > /srv/sonarqube-postgres/backups/sonarqube-postgres-backup-$$(date "+%Y-%m-%d_%H-%M").gz
             && tar -zcpf /srv/sonarqube-application-data/backups/sonarqube-application-data-backup-$$(date "+%Y-%m-%d_%H-%M").tar.gz /opt/sonarqube/data
             && find /srv/sonarqube-postgres/backups -type f -mtime +7 | xargs rm -f
             && find /srv/sonarqube-application-data/backups -type f -mtime +7 | xargs rm -f;
             sleep 24h; done'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-data-backups:/srv/sonarqube-application-data/backups
      - sonarqube-postgres-backups:/srv/sonarqube-postgres/backups
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      sonarqube:
        condition: service_healthy
    networks:
      sonarnet:
