#generate keypair for user arachni
#ansible app -m shell -a "ssh-keygen -q -b 2048 -t rsa -N '' -C 'creating SSH' -f /home/arachni/.ssh/id_rsa_arachni creates='/home/arachni/.ssh/id_rsa_arachni'" -i ol9_dasty_box -b – become-user=arachni
#ansible app -m shell -a "ls -lrt  /home/arachni/.ssh/id_rsa_arachni" -i ol9_dasty_box -b – become-user=arachni
#ansible app -m fetch -a "src='/home/arachni/.ssh/id_rsa_arachni.pub' dest='buffer/{{inventory_hostname}}-id_rsa.pub' flat='yes'" -i ol9_dasty_box -b – become-user=arachni
#ansible app -m authorized_key -a "user='arachni' state='p
---
- hosts: ol9_dasty_box
  gather_facts: no
  tasks:
    - name: create user account
      shell: |
        groupadd -r arachni
        useradd -r -g arachni arachni -m
        mkdir -p /home/arachni/.ssh
    - name: create build directory
      file:
        path: /home/arachni/build-container
        state: directory
        owner: arachni
        group: arachni
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ./dast/arachni/Dockerfile
        dest: /home/arachni/build-container/Dockerfile
        owner: arachni
        group: arachni
        mode: '0644'
    - name: build container image
      docker_image:
        name: arachni:v1.0
        build:
          path: /home/arachni/build-container/Dockerfile
          source: build
        state: present
