---
- hosts: ol9_dasty_box
  gather_facts: no
  tasks:
    - name: create user account & ssh keys
      shell: |
        groupadd -r arachni
        useradd -r -g arachni arachni -m
        mkdir -p /home/arachni/.ssh
        ssh-keygen -q -b 2048 -t rsa -N '' -C 'creating SSH' -f ~/.ssh/id_rsa_arachni creates='~/.ssh/id_rsa_arachni'
        chown -R arachni:arachni ~/.ssh
    - name: create build directory
      file:
        path: /home/arachni/build-container
        state: directory
        owner: arachni
        group: arachni
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ./dast/arachni/Dockerfile
        dest: /home/arachni/build-container/Dockerfile
        owner: arachni
        group: arachni
        mode: '0644'
    - name: build container image
      docker_image:
        name: arachni:v1.0
        build:
          path: /home/arachni/build-container/Dockerfile
          source: build
        state: present
