---
- hosts: ol9_dasty_box
  gather_facts: no
  tasks:
    - name: create user account && ssh keys
      shell: |
        groupadd -r owasp-zap
        useradd -r -g owasp-zap owasp-zap -m
        mkdir -p /home/owasp-zap/.ssh
        ssh-keygen -q -b 2048 -t rsa -N '' -C 'creating SSH' -f /home/owasp-zap/.ssh/id_rsa_owasp-zap creates='/home/owasp-zap/.ssh/id_rsa_owasp-zap'
        chown -R owasp-zap:owasp-zap /home/owasp-zap/
    - name: create build directory
      file:
        path: /home/owasp-zap/build-container
        state: directory
        owner: owasp-zap
        group: owasp-zap
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ./dast/owasp-zap/Dockerfile
        dest: /home/owasp-zap/build-container/Dockerfile
        owner: owasp-zap
        group: owasp-zap
        mode: '0644'
    - name: build container image
      docker_image:
        name: owasp-zap:v1.0
        build:
          path: /home/owasp-zap/build-container/Dockerfile
          source: build
        state: present
