---
- hosts: build_host
  gather_facts: no
  tasks:
    - name: create build directory
      file:
        path: /home/owasp-zap/build-container
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ./dast/owasp-zap/Dockerfile
        dest: /home/owasp-zap/build-container/Dockerfile
        owner: root
        group: root
        mode: '0644'
    - name: build container image
      docker_image:
        name: owasp-zap:v1.0
        build:
          path: /home/owasp-zap/build-container/Dockerfile
          source: build
        state: present