---
- hosts: ol9_dasty_box
  gather_facts: no
  tasks:
    - name: create user account
      shell: |
        groupadd -r nuclei
        useradd -r -g nuclei nuclei -m
    - name: create build directory
      file:
        path: /home/nuclei/build-container
        state: directory
        owner: nuclei
        group: nuclei
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ./dast/nuclei/Dockerfile
        dest: /home/nuclei/build-container/Dockerfile
        owner: nuclei
        group: nuclei
        mode: '0644'
    - name: build container image
      docker_image:
        name: nuclei:v1.0
        build:
          path: /home/nuclei/build-container/Dockerfile
          source: build
        state: present
