---
- hosts: ol9_dasty_box
  gather_facts: no
  tasks:
    - name: create user account
      shell: |
        groupadd -r wapiti
        useradd -r -g wapiti wapiti -m
    - name: create build directory
      file:
        path: /home/wapiti/build-container
        state: directory
        owner: wapiti
        group: wapiti
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ./dast/wapiti/Dockerfile
        dest: /home/wapiti/build-container/Dockerfile
        owner: wapiti
        group: wapiti
        mode: '0644'
    - name: build container image
      docker_image:
        name: wapiti:v1.0
        build:
          path: /home/wapiti/build-container/Dockerfile
          source: build
        state: present
